
% display best bounds found, optimal gap size, step length f
fprintf('upper bound: %14.5f ',...
  incumbent.minimumUpperBoundFound);
fprintf('| lower bound: %14.5f ', ...
  incumbent.maximumLowerBoundFound);
% fprintf('| gap size: %14.5f ', ...
%   incumbent.minimumUpperBoundFound - incumbent.maximumLowerBoundFound);
fprintf('| opt gap(%%): %8.5f ', ...
  (incumbent.minimumUpperBoundFound - incumbent.maximumLowerBoundFound)*100/incumbent.maximumLowerBoundFound);
fprintf('| open W: %3d ', ...
  length(problemReduction.openFacilities));
fprintf('| closed W: %3d ', ...
  length(problemReduction.closedFacilities));
fprintf('| iter = %4d ',...
  LLBP.totalSubgradientIterations);
fprintf('| f = %.12f ',...
  LLBP.f);
fprintf('| norm(subGrad) = %14.5f ',...
  norm(LLBP.subGrad));
fprintf('| currentLagSol: %12.5f\n', ...
  currentSolution.lowerBound);

