[ originalFormulation.m ,...
  originalFormulation.n ,...
  originalFormulation.F ,...
  originalFormulation.c ] =...
uncapacited_warehouse_location_problem_file_reader...
(originalFormulation.databasePath);