
  I_ = binarySearchWithICheckProcedure( ISorted,...
                                        client,...
                                        I,...
                                        currentFormulation.c,...
                                        currentFormulation.F );