
updateProblemReductionMaxLBByClosedFacility;

selectFacilitiesThatViolateTheMinUpperBoundFoundByClosingThem;

excludeAlreadyClosedFacilitiesFromSelectedFacilities;


openSelectedFacilities;

clear selectedFacilityIndices facilityIndex;
