
currentSolution.x(  problemReduction.fixedDemands(:, clientIndex) == 0,...
                    clientIndex) = 0;
currentSolution.x(  problemReduction.fixedDemands(:, clientIndex) == 1,...
                    clientIndex) = 1;