LLBP.T = LLBP.tau*incumbent.minimumUpperBoundFound -...
         currentSolution.lowerBound;
LLBP.T = LLBP.f*LLBP.T/( dot(LLBP.subGrad,LLBP.subGrad)   +...
                         dot(LLBP.dSubGrad,LLBP.dSubGrad) +...
                         dot(currentlyViolatedActive.dSubGrad, currentlyViolatedActive.dSubGrad) );
                  