function subGradient = threeClientSubGradient( restriction,...
                                               currentSolution )

subGradient = ...
    2*(sum(sum(currentSolution.x(restriction.S12, restriction.J)))+...
       sum(sum(currentSolution.x(restriction.S13, restriction.J)))+...
       sum(sum(currentSolution.x(restriction.S23, restriction.J))))...
     + sum(sum(currentSolution.x(restriction.S123, restriction.J)));
   
subGradient = subGradient - ...
              2 - 2*(sum(currentSolution.y(restriction.S12))+...
                     sum(currentSolution.y(restriction.S12))+...
                     sum(currentSolution.y(restriction.S23)))+...
                     sum(currentSolution.y(restriction.S123));
end