
% display best bounds found, optimal gap size, step length f
fprintf('UB: %14.3f ',...
  incumbent.minimumUpperBoundFound);
fprintf('| LB: %14.3f ', ...
  incumbent.maximumLowerBoundFound);
% fprintf('| Gap: %14.3f ', ...
%   incumbent.minimumUpperBoundFound - incumbent.maximumLowerBoundFound);
fprintf('| opt gap(%%): %8.5f ', ...
  (incumbent.minimumUpperBoundFound - incumbent.maximumLowerBoundFound)*100/incumbent.maximumLowerBoundFound);
fprintf('| open W: %2d ', ...
  length(problemReduction.openFacilities));
fprintf('| closed W: %2d ', ...
  length(problemReduction.closedFacilities));
fprintf('| iter = %4d ',...
  LLBP.totalSubgradientIterations);
fprintf('| f = %.8f ',...
  LLBP.f);
fprintf('| norm(subGrad) = %14.1f ',...
  norm([LLBP.subGrad LLBP.dSubGrad currentlyViolatedActive.dSubGrad ]));
fprintf('| LagSol: %12.1f', ...
  currentSolution.lowerBound);
fprintf('| PVAS: %3d', ...
  length(previouslyViolatedActiveSet));
fprintf('| CVAS: %3d\n', ...
  length(currentlyViolatedActive.Set));

