
updateProblemReductionMaxLBByOpenFacility;

selectFacilitiesThatViolateTheMinUpperBoundFoundByOpeningThem;

excludeAlreadyOpenFacilitiesFromSelectedFacilities;


closeSelectedFacilities;

closeDemandsFromSelectedFacilities;

clear selectedFacilityIndices facilityIndex;

